version: '3.8'
services:
    nginx:
        image: nginx:alpine
        container_name: project-1-nginx
        restart: 'always'
        volumes:
            - ./sourceCode:/var/www/html:cached
        ports:
            - 80:80
            - 443:443
        depends_on:
          - app
        networks:
          - project-1-network
    app:
        build:
            context: ./phpApacheImage
        container_name: app
        restart: 'always'
        volumes:
            - ./sourceCode:/var/www/html/
        ports:
            - 9000:80
        depends_on:
          - db
        links:
         - db:mysql     
        networks:
          - project-1-network
              
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: database-server
        environment:
            - MYSQL_ROOT_PASSWORD=111222
            - MYSQL_DATABASE=docker-db
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=mypw
            
        ports:
            - 3306:3306
        networks:
          - project-1-network
        
    phpmyadmin:
        image: phpmyadmin
        ports:
            - 9001:80
        restart: always
        environment:
          - PMA_ARBITRARY=1
        networks:
          - project-1-network
        links:
         - db:mysql  


networks:
    project-1-network:
     driver: bridge

volumes:
  project-1-volume:
    driver: local     